config/routes.rb
Rails.application.routes.draw do

  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  post 'logout', to: 'sessions#destroy'

  root 'dashboard#home'  

  resources :templates do
    get 'preview', to: 'templates#preview'
  end

  resources :requests, only: [:index] do
    get 'download', to: 'requests#download'
    get 'mail', to: 'requests#mail'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
# frozen_string_literal: true

#:nodoc:
class City < MadappDbBase
  self.table_name = 'User'

  has_many :users
end

app/models/concerns/madapp_authenticable.rb
module MadappAuthenticable
  extend ActiveSupport::Concern

  def authenticate(password)
    hash = self.password_hash.gsub(/^\$2y/, '$2a')
    if ::BCrypt::Password.new(hash) == password
      self
    else
      false
    end    
  end
end

app/models/group.rb
# frozen_string_literal: true

#:nodoc:
class Group < MadappDbBase
  self.table_name = 'Group'

  def self.types
    %w[volunteer fellow strat national executive]
  end
  has_many :user_groups
  has_many :users, through: :user_groups
end

app/models/madapp_db_base.rb
class MadappDbBase < ActiveRecord::Base  
  self.abstract_class = true
  establish_connection MADAPP_DB
end

app/models/request.rb
class Request < ApplicationRecord
  serialize :data

  belongs_to :template
  belongs_to :user

  validates_uniqueness_of :user_id
end

app/models/template.rb
class Template < ApplicationRecord
end

app/models/user.rb
# frozen_string_literal: true

#:nodoc:
class User < MadappDbBase
  self.table_name = 'User'

  has_many :user_credits_history
  has_many :requests
  has_many :user_groups
  has_many :groups, through: :user_groups
  include MadappAuthenticable
end

app/models/user_credits_history.rb
class UserCreditsHistory < MadappDbBase
  self.table_name = 'User_Credit_Archive'

  belongs_to :user
end

app/models/user_group.rb
# frozen_string_literal: true

#:nodoc:
class UserGroup < MadappDbBase
  self.table_name = 'UserGroup'

  belongs_to :user
  belongs_to :group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate!

  def authenticate!
    redirect_to login_path and return unless current_user.present?
  end

  def current_user
    @_current_user ||= User.find_by(id: session[:user])
  end

  def after_login_path
    root_path
  end

  def after_logout_path
    login_path
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def home
    @user = current_user
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:download, :mail]

  def index
    @requests = Request.where(user_id: current_user.id)
  end

  def download
    respond_to do |format|
      format.pdf do
        @document = Document::PDF.call(template: @request.template,
                                       data: @request.data).data
        send_data @document,
                  filename: "#{@request.template.name}.pdf",
                  type: 'application/pdf'
      end
    end
  end

  def mail
    RequestMailer.document_email(@request.id).deliver_later
    flash.now[:success] = 'Email triggered'
    redirect_to requests_path
  end

  private

  def set_request
    request_id = params[:id] || params[:request_id]
    @request = Request.find_by(id: request_id)
    #
    unless @request.present?
      flash.now[:notice] = 'Request not found'
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/sessions_controller.rb
# TODO: extract this to MADapp Login rails engine
class SessionsController < ApplicationController
  skip_before_action :authenticate!, only: [:new, :create]

  def new
    @user = User.new
  end
  
  def create
    result = User::Authentication.call(session_params)
    if result.success?
      session[:user] = result.data.id
      flash[:info] = "Welcome #{current_user.name}!"
      redirect_to after_login_path
    else
      flash[:error] = result.message
      redirect_to login_path
    end
  end

  def destroy
    session[:user] = nil
    redirect_to after_logout_path
  end

  private 

  def session_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/templates_controller.rb
class TemplatesController < ApplicationController
  before_action :set_template, only: [:edit, :update, :destroy, :preview]
  
  def index
    @templates = Template.all
  end

  def preview
    @data = template_data
    respond_to do |format|
      @data = OpenStruct.new(@data)
      format.html { render pdf: 'Sample',
                           template: 'templates/preview',
                           layout: false,
                           page_size: 'A5',
                           margin: { top: 0, bottom: 0, right: 0, left: 0 },
                           show_as_html: true,
                           orientation: :landscape,
                           print_media_type: true,
                           background: true,
                           no_background: false }
      format.pdf do
        @preview = Document::PDF.call(template: @template, data: @data).data
        send_data @preview,
                  filename: "Preview #{@template.name}.pdf",
                  type: 'application/pdf' 
      end
    end     
  end

  def new
    @template = Template.new
  end

  def create
    @template = Template.create(template_params)
    redirect_to templates_path
  end

  def edit
  end

  def update
    if @template.update(template_params)
      flash.now[:info] = 'Templated Updated'
    else
      flash.now[:danger] = "Unable to update template. #{@template.full_messages.errors.to_sentence}"
    end
    redirect_to templates_path
  end

  def destroy

  end

  private 

  def set_template
    template_id = params[:id] || params[:template_id]
    @template = Template.find_by(id: template_id)
    unless @template.present?
      flash.now[:notice] = 'Template not found'
      redirect_back(fallback_location: root_path  )
    end
  end

  def template_params
    params.require(:template).permit!
  end

  def template_data
    { name: 'Sample Name',
      city: 'Sample City',
      primary_role: 'Sample Role',
      additional_roles: 'Extra roles' }
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper #:nodoc:

  def display_flash(key, value)
    render partial: 'layouts/flash', locals: { key: key, value: value }
  end

  def notifications?
    # TODO: return true if there are notifications for user
    false
  end

  def unread_notifications?
    # TODO: return true if there are unread notifications
    false
  end

  def initials(name)
    name.split.map(&:first).join
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user])
  end

  def safe_base64(data)
    Rack::Utils.escape(Base64.encode64(data).gsub(/\s+/, ''))
  end
end

app/helpers/requests_helper.rb
# frozen_string_literal: true

module RequestsHelper #:nodoc:
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper #:nodoc:
end

app/helpers/templates_helper.rb
# frozen_string_literal: true

module TemplatesHelper #:nodoc:
end

app/views/dashboard/certificate.pdf.haml
.main
  %center
    %p
      This is to celebrate the contributions of
      %br
      %span.input{ style: 'width: 300px;'}
        = 'Test'
      %br
      to the /
      %span.input{ style: 'width: 200px;'} 
        = 'Test'
      chapter of
      %br
      Make A Difference during
      %span.input{ style: 'width: 150px;'}
        2016 - 2017
      \.
      %br
      As a part of the chapter, he/she fulfilled the
      %br
      responsibilities of a
      %br
      %span.input{ style: 'width: 300px;'}
      = 'Test'
      <br>
      - if true
        as well as 
        %span.input{ style: 'width: 200px;'}
        = 'Test'
        %br  
      and was a valuable asset in
      %br
      delivering MAD's vision of better
      %br
      outcomes for children in shelters.
.footer
  %p
    Make A Difference is a youth driven, non-profit organisation working to ensure better outcomes for children in shelter homes. MAD's vision is to ensure that even the most vulnerable children in society are able to realize equitable outcomes. Our minimum target is to ensure that they surpass the threshold of middle class. Our Mission is to ensure that all children in shelters accross India are able to realize better outcomes within the next 25 years, by mobilizing the community, enabling the sector, empowering the child, and changing the ecosystem.

app/views/dashboard/home.html.haml
= content_for :title do
  %h4 Dashboard

= link_to 'Documents', requests_path, class: 'btn btn-primary'

app/views/layouts/_flash.html.haml
%div{ class: "alert alert-#{type}", data: { dismiss: 'alert' } }
  %button.close
  = msg if msg.is_a?(String)

app/views/layouts/_header.html.haml
.header.py-4
  .container
    .d-flex
      .header-brand
        MAD-ACCREDIT
      .d-flex.order-lg-2.ml-auto
        .dropdown.d-none.d-md-flex
          %a.nav-link.icon
            - if notifications?
              %i.fe.fe-bell
              -if unread_notifications?
                %span.nav-unread
            - else 
              %i.fe.fe-bell-off
        - if current_user.present?
          .dropdown.show
            %a.nav-link.pr-0.leading-none{ data: { toggle: 'dropdown'}, aria: { expanded: true } }
              %span.avatar
                = current_user.user_type.first.upcase
              %span.ml-2.d-none.d-lg-block
                %span.text-default
                  = current_user.name
                %span.text-muted.d-block.mt-1
                  = 'Admin'
          = form_with scope: :user, url: logout_path, method: :post do |f| 
            = f.submit 'Logout', class: 'btn btn-danger float-right'
        - else
          


        
      
          

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= t('title')
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .page
      .page-main
        = render 'layouts/header'
        .container.flash
          - flash.each do |type,msg|
            = render partial: 'layouts/flash', locals: { type: type, msg: msg }
        .my-3.my-md-5
          .container
            .page-header
              .page-title
                = yield :title
            = yield
      -# = render 'layouts/footer'

app/views/layouts/pdf.html.haml
!!!

%html
  %head
    %meta{ charset: 'utf-8' }
    %title
      Volunteer Certificat    
  = wicked_pdf_stylesheet_link_tag 'certificate.css'
  = stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Roboto+Condensed'
  - background = 'background.jpg'
  %body{ style: "height: 400px; width: 500px; background-image: url('#{wicked_pdf_asset_base64(background)}'); background-position: center center; background-size: cover;" }
    = yield
  

app/views/requests/index.html.haml
= content_for :title do
  %h4 Documents

.col-sm-6.col-md-8
  .card
    .card-header
      Available Documents
      = link_to new_template_path, class: 'btn btn-sm btn-pill btn-secondary ml-auto' do
        %i.fe.fe-plus
    %table.table.card-table
      %tbody
        - @requests.each do |request|
          %tr
            %td
              %i.fe.fe-arrow-right.text-muted
            %td
              = request.document
            %td.btn-list.text-right
              = link_to request_download_url(request.id, format: :pdf),
                        class: 'btn btn-info btn-pill btn-space' do
                %i.fe.fe-download
                Download
              = link_to request_mail_url(request.id),
                        class: 'btn btn-info btn-pill btn-space' do 
                %i.fe.fe-mail
                Email

app/views/templates/_document.html.haml
!!!
%html
  %head
    %meta{ charset: 'utf-8' }
    = render 'templates/style', { template: template }
    %title
      Volunteer Certificate  
  %body{ class: 'A5 landscape' }
    .sheet.background
      = render inline: template.html, type: template.engine, layout: false, locals: { data: data }
        

app/views/templates/_form.html.haml
= form_with model: template, class: 'card' do |f|
  .card-body
    .container
      .row
        .card-title
          Template Data
        .btn-list.ml-auto
          = f.submit method: :post, class: 'btn btn-primary btn-space ' do 
            Save 
    %fieldset.form-fieldset
      .row
        .col-4
          .form-group
            = f.label :name, class: 'form-label'
            = f.text_field :name, class: 'form-control', value: template.name
      .row
        .col-12
          .form-group
            = f.label :haml, class: 'form-label'
            = f.text_area :html, class: 'form-control', rows: 10, cols: 20, value: template.html
            = f.hidden_field :engine, value: 'haml'
      .row
        .col-12
          .form-group
            = f.label :css, class: 'form-label'
            = f.text_area :css, class: 'form-control', rows: 10, cols: 20, value: template.css

app/views/templates/_style.html.erb
<%= stylesheet_link_tag 'paper' %>
<%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Roboto+Condensed' %>
<style>
@page { size: A5 landscape }
@media screen {
  .background {
    background-image: url('data:image/jpeg;base64,<%= safe_base64(template.body_bg_img)%>');
    background-position: center;
    background-attachment: unset;
    background-size: cover;
    background-repeat: no-repeat;
  }
}
@media print {
  body {
    background-image: url('data:image/jpeg;base64,<%= safe_base64(template.body_bg_img)%>');
    background-position: inherit;
    background-attachment: unset;
    background-size: cover;
    background-repeat: no-repeat;
  }
}
<%= render inline: template.css, type: 'css' %>
</style>
    

app/views/templates/edit.html.haml
= content_for :title do
  %h4 Edit Template

= render partial: 'templates/form', locals: { template: @template }

app/views/templates/index.html.haml
= content_for :title do
  %h4 Templates

.col-sm-6.col-md-8
  .card
    .card-header
      Available Templates
      = link_to new_template_path, class: 'btn btn-sm btn-pill btn-secondary ml-auto' do
        %i.fe.fe-plus
    %table.table.card-table
      %tbody
        - @templates.each do |template|
          %tr
            %td
              %i.fe.fe-arrow-right.text-muted
            %td
              = template.name
            %td.btn-list.text-right
              = link_to edit_template_path(template), class: 'btn btn-pill btn-secondary' do
                %i.fe.fe-edit 
                Edit
              = link_to template_preview_url(template.id, format: :pdf),
                        class: 'btn btn-info btn-pill btn-space' do
                %i.fe.fe-download
                Download
              = link_to template_preview_url(template.id, format: :html),
                        target: :_blank,
                        class: 'btn btn-success btn-pill btn-space' do 
                HTML

app/views/templates/new.html.haml
= content_for :title do 
  %h4 New Template

= render partial: 'templates/form', locals: { template: @template }

app/views/templates/preview.html.haml
= render partial: 'templates/document', locals: { template: @template, data: @data }